-- noinspection SqlResolveForFile

INSERT INTO CITY (ID, "NAME", COUNTRY) VALUES (111, 'Pingtan', 'Germany');
INSERT INTO CITY (ID, "NAME", COUNTRY) VALUES (222, 'Soutelo', 'UK');
INSERT INTO CITY (ID, "NAME", COUNTRY) VALUES (333, 'Waterbury', 'US');

INSERT INTO ADDRESS (ID, STREET, CITY_ID) VALUES (11, '7113 Stuart Hill', 111);
INSERT INTO ADDRESS (ID, STREET, CITY_ID) VALUES (22, '9 Westend Terrace', 222);
INSERT INTO ADDRESS (ID, STREET, CITY_ID) VALUES (33, '7125 Birchwood Court', 333);

INSERT INTO PERSON (ID, FIRSTNAME, LASTNAME, ADDRESS_ID) VALUES (1, 'Nicolais', 'Twinning', 11);
INSERT INTO PERSON (ID, FIRSTNAME, LASTNAME, ADDRESS_ID) VALUES (2, 'Mickie', 'Cresswell', 22);
INSERT INTO PERSON (ID, FIRSTNAME, LASTNAME, ADDRESS_ID) VALUES (3, 'Rose', 'Garrow', 33);